import {StyleSheet} from "react-native";
/* --- Styles --- */
export const styles = StyleSheet.create({
  innerContainer: {
    backgroundColor: "#f8f9fa",
    borderRadius: 25,
    width: "100%",
    height: "100%",
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
  },
  header: {
    height: 120,
    backgroundColor: "#6f42c1",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 30,
  },
  headerText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 24,
  },
  headerItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerIcon: {
    fontSize: 20,
    marginRight: 8,
    color: "#fff",
  },
  restaurantHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 20,
    paddingTop: 10,
  },
  restaurantIcon: {
    fontSize: 20,
    marginRight: 8,
  },
  safetext: {
    color: "#6f42c1",
    fontWeight: "bold",
    fontSize: 24,
    marginTop: -5, // fixed instead of invalid padding
  },
  safeArea: { flex: 1 },
  content: {
    flex: 1,
    flexDirection: "row",
    margin: 10,
    marginTop: -30,
  },
  leftColumn: { flex: 2, marginRight: 8 },
  rightColumn: { flex: 1 },

  /* Reusable box */
  box: {
    flex: 0.82,
    borderRadius: 17,
    marginBottom: 10,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    padding: 8,
  },
  lightBlueBox: {
    flex: 1,
    borderRadius: 17,
    marginBottom: 10,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    paddingHorizontal: 15,
    paddingVertical: 15,
  },
  greenBox: {
    height: 220,
    borderRadius: 16,
    margin: 14,
    marginTop: 16,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    padding: 15,
  },

  /* Box text */
  boxTitle: {
    color: "#2d3436",
    fontWeight: "bold",
    fontSize: 11,
    marginBottom: 4,
    textAlign: "center",
  },
  subTitle: {
    color: "#636e72",
    fontWeight: "600",
    fontSize: 9,
    marginBottom: 4,
    textAlign: "center",
  },
  statsContainer: { flex: 1 },
  statRow: { flexDirection: "row", marginBottom: 2 },
  statLabel: { flex: 1, paddingHorizontal: 2 },
  statValue: { flex: 1, paddingHorizontal: 2, alignItems: "flex-end" },
  statLabelText: { color: "#636e72", fontWeight: "600", fontSize: 8 },
  statValueText: { color: "#2d3436", fontWeight: "bold", fontSize: 9 },
  commentHighlight: {
    color: "#2d3436",
    fontStyle: "italic",
    fontSize: 10,
    textAlign: "center",
    marginTop: 5,
  },

  /* Table */
  tableTitle: { color: "#2d3436", fontWeight: "bold", fontSize: 16, marginBottom: 10 },
  tableContainer: { flex: 1, backgroundColor: "#f8f9fa", borderRadius: 10 },
  tableHeader: { flexDirection: "row", backgroundColor: "#e9ecef", paddingVertical: 8 },
  tableHeaderText: {
    flex: 1,
    color: "#495057",
    fontWeight: "bold",
    fontSize: 11,
    textAlign: "center",
  },
  tableRow: { flexDirection: "row", paddingVertical: 6 },
  tableCellText: {
    flex: 1,
    fontSize: 10,
    textAlign: "center",
    color: "#495057",
  },
  tableActionText: {
    flex: 1,
    fontSize: 10,
    textAlign: "center",
    color: "#6f42c1",
    fontWeight: "bold",
  },

  /* Alert content */
  contentPadding: { marginBottom: 10 },
  alertTitle: { color: "#2d3436", fontWeight: "bold", fontSize: 18, marginBottom: 5 },
  orderNumber: { color: "#495057", fontWeight: "600", fontSize: 16 },
  itemName: { color: "#2d3436", fontWeight: "bold", fontSize: 16, marginBottom: 3 },
  commentText: { color: "#2d3436", fontSize: 14, marginBottom: 10 },
  buttonContainer: { flexDirection: "row", marginTop: 10, gap: 10 },
  buttonWrapper: { alignItems: "center" },
  buttonText: {
    backgroundColor: "#6f42c1",
    color: "#fff",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    fontWeight: "bold",
    fontSize: 12,
  },

  /* Tags */
  tagContainer: { flexDirection: "row", marginTop: 5, flexWrap: "wrap" },
  tag: {
    backgroundColor: "#e9ecef",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 6,
    marginBottom: 4,
  },
  tagText: { color: "#495057", fontSize: 10, fontWeight: "600" },
});